apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: svcapp
  labels:
    app: app
spec:
  ports:
    - port: 80
  selector:
    app: app
